<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Techspot\SendQuote\Block\Link $block */
?>
<li class="link sendquote" data-bind="scope: 'sendquote'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= $block->escapeHtml($block->getLabel()) ?>
        <!-- ko if: sendquote().counter -->
        <span data-bind="text: sendquote().counter" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sendquote": {
                        "component": "Techspot_SendQuote/js/view/sendquote"
                    }
                }
            }
        }
    }

</script>
