<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Share\Sendquote $block */
?>

<?php if ($block->hasSendquoteItems()): ?>
    <form class="form shared sendquote" action="<?= $block->escapeUrl($block->getUrl('sendquote/index/update')) ?>" method="post">
        <div class="sendquote table-wrapper">
            <table class="table data sendquote" id="sendquote-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Quote')) ?></caption>
                <thead>
                <tr>
                    <th class="col product" scope="col"><?= $block->escapeHtml(__('Product')) ?></th>
                    <th class="col comment" scope="col"><?= $block->escapeHtml(__('Comment')) ?></th>
                    <th class="col actions" scope="col"><?= $block->escapeHtml(__('Add to Cart')) ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getSendquoteItems() as $item): ?>
                    <?php
                    $product = $item->getProduct();
                    $isVisibleProduct = $product->isVisibleInSiteVisibility();
                    ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="col product">
                            <a class="product photo" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
                                <?= $block->getImage($product, 'customer_shared_sendquote')->toHtml() ?>
                            </a>
                            <strong class="product name">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                                    <?= $block->escapeHtml($product->getName()) ?>
                                </a>
                            </strong>
                            <?php
                                echo $block->getProductPriceHtml(
                                    $product,
                                    'sendquote_configured_price',
                                    \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                    ['item' => $item]
                                );
                            ?>
                            <?= $block->getDetailsHtml($item) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="col comment"><?= /* @noEscape */ $block->getEscapedDescription($item) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="col actions" data-role="add-to-links">
                            <?php if ($product->isSaleable()): ?>
                                <?php if ($isVisibleProduct): ?>
                                    <button type="button"
                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                            data-post='<?= /* @noEscape */ $block->getSharedItemAddToCartUrl($item) ?>'
                                            class="action tocart">
                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                    </button>
                                <?php endif ?>
                            <?php endif; ?>
                            <a href="#" data-post='<?= /* @noEscape */ $block->getAddToSendquoteParams($item) ?>'  onclick="location.assign(this.href); return false;" class="action tosendquote" data-action="add-to-sendquote">
                                <span><?= $block->escapeHtml(__('Add to Quotation')) ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>

        <div class="actions-toolbar">
            <?php if ($block->isSaleable()):?>
                <div class="primary">
                    <button type="button"
                            title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>"
                            data-post='<?= $block->escapeUrl($block->getSharedAddAllToCartUrl()) ?>'
                            class="action tocart primary">
                        <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
                    </button>
                </div>
            <?php endif;?>
            <div class="secondary">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>
    </form>
<?php else: ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('Quote is empty now.')) ?></div></div>
<?php endif ?>
