<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Cart\Item\Renderer\Actions\MoveToSendquote $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
    <a href="#"
       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
       class="use-ajax action action-tosendquote">
        <span><?= $block->escapeHtml(__('Move to Sendquote')) ?></span>
    </a>
<?php endif ?>
