<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Catalog\Product\View\AddTo\Sendquote $block */
?>
<?php if ($block->isSendQuoteAllowed()) : ?>
    <a href="#"
       class="action primary tosendquote"
       data-post='<?= /* @noEscape */ $block->getSendquoteParams() ?>'
       data-action="add-to-sendquote"><span><?= $block->escapeHtml(__('Add to Quotation')) ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToSendquote": <?= /* @noEscape */ $block->getSendquoteOptionsJson() ?>
        }
    }
</script>
