<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<tr>
    <td class="col-product-sku"><span><?= /* @escapeNotVerified */ $block->getItemProductColumn($_item, 'sku') ?></span></th>
    <td class="col-product-name"><span><?= /* @escapeNotVerified */ $block->getItemProductColumn($_item, 'name') ?></span></th>
    <td class="col-store-id"><span><?= /* @escapeNotVerified */ $block->getStoreName($_item->getStoreId()) ?></span></th>
    <td class="col-description"><?= /* @escapeNotVerified */ $_item->getDescription() ?></td>
    <td class="col-qty"><?= /* @escapeNotVerified */ $_item->getQty()*1 ?></td>
    <td class="col-price"><?= /* @escapeNotVerified */ $block->getFormatedPrice($_item->getPrice()) ?></td>
    <td class="col-custom-price"><input type="text" name="quotation[items][<?= /* @escapeNotVerified */ $_item->getSendquoteItemId() ?>][custom-price]" value="<?= /* @escapeNotVerified */ $_item->getCustomPrice() ?>"/></td>
    <td class="col-total last"><?= /* @escapeNotVerified */ $block->getFormatedPrice($block->getItemSubtotal($_item)) ?></td>
</tr>