<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Item\Configure $block */
?>
<?php if ($this->helper('Techspot\SendQuote\Helper\Data')->isAllow()) : ?>
    <a href="#" data-post='<?= /* @noEscape */ $block->getUpdateParams() ?>' class="action tosendquote updated" data-action="add-to-sendquote">
        <span><?= $block->escapeHtml(__('Update Quotation')) ?></span>
    </a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToSendquote": <?= /* @noEscape */ $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getSendquoteOptions()) ?>
        }
    }
</script>
