<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Rss\Link $block */
?>
<?php if ($block->isRssAllowed() && $block->getLink() && $this->helper('Techspot\SendQuote\Helper\Data')->getSendquote()->getItemsCount()): ?>
    <a href="<?= $block->escapeUrl($block->getLink()) ?>" class="action rss sendquote">
        <span><?= $block->escapeHtml(__('RSS Feed')) ?></span>
    </a>
<?php endif; ?>
