<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Customer\Sendquote\Item\Column\Actions $block */
?>
<?php $children = $block->getChildNames(); ?>
<?php if ($children): ?>
    <div class="<?= $block->escapeHtmlAttr($block->getCssClass()) ?>">
        <?php foreach ($children as $childName):?>
            <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
        <?php endforeach;?>
    </div>
<?php endif; ?>
