<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Techspot\SendQuote\Block\Customer\Sendquote\Item\Column\Comment $block  */

/* @var \Techspot\SendQuote\Model\Item $item */
$item = $block->getItem();
?>

<div class="field comment-box">
    <label class="label" for="product-item-comment-<?= $block->escapeHtmlAttr($item->getSendquoteItemId()) ?>">
        <span><?= $block->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="control">
        <textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getSendquoteItemId()) ?>" placeholder="<?= /* @noEscape */ $this->helper('Techspot\SendQuote\Helper\Data')->defaultCommentString() ?>" name="description[<?= $block->escapeHtmlAttr($item->getSendquoteItemId()) ?>]" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="product-item-comment"><?= ($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
