<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Customer\Sendquote\Item\Column\Image $block */

/** @var \Techspot\SendQuote\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<?php /*
<a class="product-item-photo" tabindex="-1" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
    <?= $block->getImage($product, 'sendquote_thumbnail')->toHtml() ?>
</a>
*/ ?>
