<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Customer\Sendquote\Item\Column\Info $block */

/** @var \Techspot\SendQuote\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<span class="price">
    <?php if(null != $item->getCustomPrice()): ?>
        <?= $block->escapeHtml($block->getCustomPrice($item)) ?>
    <?php else: ?>
        <?= /* @escapeNotVerified */ __('Waiting Quotation') ?>
    <?php endif; ?>
</span>