<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Customer\Sendquote\Item\Column\Cart $block */

/** @var \Techspot\SendQuote\Model\Item $item */
$item = $block->getItem();
?>
<span class="qty"><?= /* @escapeNotVerified */  (int)($block->getAddToCartQty($item) * 1) ?></span>