<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Techspot\SendQuote\Block\Customer\Sendquote\Item\Column\Cart $block */

/** @var \Techspot\SendQuote\Model\Item $item */
$item = $block->getItem();
?>
<div class="field qty-box">
    <label class="label" for="product-item-qty-<?= $block->escapeHtmlAttr($item->getSendquoteItemId()) ?>">
            <span><?= $block->escapeHtml(__('Qty')) ?></span>
    </label>
    <div class="control">
        <input id="product-item-qty-<?= $block->escapeHtmlAttr($item->getSendquoteItemId()) ?>" name="qty[<?= $block->escapeHtmlAttr($item->getSendquoteItemId()) ?>]" title="<?= $block->escapeHtmlAttr(__('qty')) ?>" class="product-item-qty" value="<?= /* @escapeNotVerified */  (int)($block->getAddToCartQty($item) * 1) ?>"/>
    </div>
<!--span class="qty"><?= /* @escapeNotVerified */  (int)($block->getAddToCartQty($item) * 1) ?></span-->
</div>