<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Techspot\SendQuote\Block\Catalog\Product\ProductList\Item\AddTo\Sendquote $block */
?>
<?php if ($block->isSendQuoteAllowed()): ?>
    <a href="#"
       class="action tosendquote"
       title="<?= $block->escapeHtmlAttr(__('Add to Quotation')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Quotation')) ?>"
       data-post='<?= /* @noEscape */ $block->getAddToSendquoteParams($block->getProduct()) ?>'
       data-action="add-to-sendquote"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Quotation')) ?></span>
    </a>
<?php endif; ?>
