<?php
/**
 * Copyright © TechSpot Web Agency. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var Techspot\SendQuote\Block\Adminhtml\Sendquote\View\Form $block
 */
$quotation = $block->getSendquote();
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Quotation & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <?php //$confirmationEmailStatusMessage = $order->getEmailSent() ? __('The order confirmation email was sent') : __('The order confirmation email is not sent'); ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?= $block->escapeHtml(__('Quotation #%1', $quotation->getSendquoteId())) ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Quotation Date')) ?></th>
                    <td><?= $block->formatDate($quotation->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Quotation Status')) ?></th>
                    <td><span id="quotation_status"><?= $block->escapeHtml($quotation->getStatusName($quotation->getStatus())) ?></span></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Expirate Date')) ?></th>
                    <td><?= $block->formatDate($quotation->getShelfLife(), \IntlDateFormatter::MEDIUM, false) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Quotation Last Update')) ?></th>
                    <td><?= $block->formatDate($quotation->getUpdatedAt(), \    IntlDateFormatter::MEDIUM) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Comments')) ?></th>
                    <td><?= $quotation->getDescription() ?></td>
                </tr>

                <tr>
                    <th><?= $block->escapeHtml(__('Sent to the Customer')) ?></th>
                    <td><?= __('Sent %1 times', $quotation->getSentCustomer()) ?></td>
                </tr>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Account Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <span><?= $block->escapeHtml($block->getCustomerName()); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Email')) ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($block->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($block->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><span><?= $block->escapeHtml($groupName) ?></span></td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
    </div>
    
</section>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Items Quotation') ?></span>
    </div>
    <?= $block->getChildHtml('quotation_items'); ?>
</section>